// ─── Pakistan Geography (Province → District → Tehsils) ──────────────────────
export const geoData = {
  "Punjab": {
    "Lahore":           ["Lahore City", "Lahore Cantt", "Raiwind", "Shalimar"],
    "Rawalpindi":       ["Rawalpindi", "Gujar Khan", "Taxila", "Kahuta", "Murree", "Kotli Sattian"],
    "Faisalabad":       ["Faisalabad City", "Faisalabad Sadar", "Jaranwala", "Sammundri", "Tandlianwala", "Chak Jhumra"],
    "Multan":           ["Multan City", "Multan Sadar", "Shujabad", "Jalalpur Pirwala"],
    "Gujranwala":       ["Gujranwala City", "Gujranwala Sadar", "Kamoke", "Nowshera Virkan", "Wazirabad"],
    "Sialkot":          ["Sialkot City", "Sialkot Sadar", "Daska", "Pasrur", "Sambrial"],
    "Sargodha":         ["Sargodha City", "Bhalwal", "Sahiwal (Sargodha)", "Silanwali", "Kot Momin"],
    "Bahawalpur":       ["Bahawalpur City", "Hasilpur", "Yazman", "Khairpur Tamewali"],
    "Rahim Yar Khan":   ["Rahim Yar Khan", "Sadiqabad", "Liaqatpur", "Khanpur"],
    "Kasur":            ["Kasur", "Chunian", "Pattoki"],
    "Sheikhupura":      ["Sheikhupura", "Nankana Sahib", "Safdarabad", "Muridke"],
    "Jhang":            ["Jhang City", "Shorkot", "Ahmed Pur Sial"],
    "Gujrat":           ["Gujrat City", "Kharian", "Lalamusa"],
    "Narowal":          ["Narowal", "Shakargarh"],
    "Mandi Bahauddin":  ["Mandi Bahauddin", "Phalia", "Malikwal"],
    "Chakwal":          ["Chakwal", "Talagang", "Choa Saidan Shah"],
    "Jhelum":           ["Jhelum", "Sohawa", "Pind Dadan Khan"],
    "Hafizabad":        ["Hafizabad", "Pindi Bhattian"],
    "Okara":            ["Okara", "Renala Khurd", "Depalpur"],
    "Vehari":           ["Vehari", "Mailsi", "Burewala"],
    "Khanewal":         ["Khanewal", "Mian Channu", "Kabirwala"],
    "Lodhran":          ["Lodhran", "Kehror Pacca", "Dunyapur"],
    "Pakpattan":        ["Pakpattan", "Arifwala"],
    "Bahawalnagar":     ["Bahawalnagar", "Chishtian", "Fort Abbas", "Harunabad"],
    "Muzaffargarh":     ["Muzaffargarh", "Kot Adu", "Alipur", "Jatoi"],
    "Layyah":           ["Layyah", "Karor Lal Esan", "Chaubara"],
    "Bhakkar":          ["Bhakkar", "Mankera", "Darya Khan"],
    "Khushab":          ["Khushab", "Noorpur", "Quaidabad", "Joharabad"],
    "DG Khan":          ["DG Khan City", "Taunsa", "Kot Chutta"],
    "Rajanpur":         ["Rajanpur", "Jampur", "Rojhan"],
    "Mianwali":         ["Mianwali", "Piplan", "Isa Khel"],
    "Sahiwal":          ["Sahiwal City", "Chichawatni"],
    "Chiniot":          ["Chiniot", "Bhawana", "Lalian"],
    "Toba Tek Singh":   ["Toba Tek Singh", "Gojra", "Kamalia"],
    "Nankana Sahib":    ["Nankana Sahib", "Sangla Hill", "Sharaqpur"],
  },
  "Sindh": {
    "Karachi":              ["Karachi Central", "Karachi East", "Karachi South", "Karachi West", "Korangi", "Malir"],
    "Hyderabad":            ["Hyderabad City", "Latifabad", "Qasimabad"],
    "Sukkur":               ["Sukkur", "Rohri", "Salehpat"],
    "Larkana":              ["Larkana", "Dokri", "Ratodero"],
    "Mirpur Khas":          ["Mirpur Khas", "Jhuddo", "Kot Ghulam Muhammad"],
    "Nawabshah (SBA)":      ["Nawabshah", "Sakrand", "Qazi Ahmad"],
    "Jacobabad":            ["Jacobabad", "Thul", "Garhi Khairo"],
    "Khairpur":             ["Khairpur", "Kingri", "Gambat", "Kotdiji"],
    "Shikarpur":            ["Shikarpur", "Lakhi", "Garhi Yasin"],
    "Dadu":                 ["Dadu", "Johi", "Mehar"],
    "Thatta":               ["Thatta", "Sujawal", "Mirpur Sakro"],
    "Badin":                ["Badin", "Talhar", "Tando Bago"],
    "Sanghar":              ["Sanghar", "Shahdadpur", "Tando Adam"],
    "Umerkot":              ["Umerkot", "Kunri", "Samaro"],
    "Ghotki":               ["Ghotki", "Obaro", "Mirpur Mathelo"],
    "Kashmore":             ["Kashmore", "Kandhkot", "Tangwani"],
    "Naushahro Feroze":     ["Naushahro Feroze", "Moro", "Bhiria Road"],
    "Kambar-Shahdadkot":    ["Kambar", "Shahdadkot", "Warah"],
    "Jamshoro":             ["Jamshoro", "Kotri", "Manjhand"],
    "Matiari":              ["Matiari", "Hala", "Saeedabad"],
    "Tando Allahyar":       ["Tando Allahyar", "Chambar"],
    "Tharparkar":           ["Mithi", "Islamkot", "Diplo"],
  },
  "Khyber Pakhtunkhwa (KPK)": {
    "Peshawar":     ["Peshawar City", "Peshawar Sadar", "Nauthia Qadeem"],
    "Mardan":       ["Mardan", "Takht Bhai"],
    "Swat":         ["Saidu Sharif", "Matta", "Bahrain", "Kabal", "Khwazakhela", "Charbagh"],
    "Abbottabad":   ["Abbottabad", "Havelian", "Bagra"],
    "Nowshera":     ["Nowshera", "Pabbi", "Jehangira"],
    "Charsadda":    ["Charsadda", "Shabqadar", "Tangi"],
    "Mansehra":     ["Mansehra", "Balakot", "Oghi"],
    "Kohat":        ["Kohat", "Lachi", "Dara Adam Khel"],
    "Bannu":        ["Bannu", "Domel", "Miryan"],
    "DI Khan":      ["DI Khan City", "Paharpur", "Tank"],
    "Haripur":      ["Haripur", "Ghazi", "Tarbela"],
    "Malakand":     ["Malakand", "Batkhela"],
    "Shangla":      ["Alpuri", "Puran", "Bisham"],
    "Dir Lower":    ["Timergara", "Adenzai", "Balambat"],
    "Dir Upper":    ["Dir Upper City", "Kumrat"],
    "Buner":        ["Daggar", "Sowari", "Totalai"],
    "Swabi":        ["Swabi", "Razar", "Topi"],
    "Karak":        ["Karak", "Banda Daud Shah"],
    "Lakki Marwat": ["Lakki Marwat", "Serai Naurang"],
    "Hangu":        ["Hangu", "Thall"],
    "Chitral":      ["Chitral City", "Drosh", "Mastuj"],
    "Bajaur":       ["Khar", "Nawagai"],
    "Mohmand":      ["Ghalanai", "Ekka Ghund"],
  },
  "Balochistan": {
    "Quetta":           ["Quetta City", "Satellite Town", "Zarghoon Road"],
    "Khuzdar":          ["Khuzdar", "Wadh", "Ornach"],
    "Gwadar":           ["Gwadar City", "Pasni", "Ormara"],
    "Turbat (Kech)":    ["Turbat", "Mand", "Tump"],
    "Chagai":           ["Dalbandin", "Nok Kundi"],
    "Nasirabad":        ["Dera Murad Jamali", "Tamboo"],
    "Panjgur":          ["Panjgur City", "Gichk"],
    "Mastung":          ["Mastung", "Dasht"],
    "Pishin":           ["Pishin", "Karezat"],
    "Kalat":            ["Kalat", "Surab", "Mangochar"],
    "Loralai":          ["Loralai", "Barkhan", "Duki"],
    "Sibi":             ["Sibi", "Lehri", "Harnai"],
    "Zhob":             ["Zhob", "Muslim Bagh"],
    "Dera Bugti":       ["Dera Bugti", "Sui"],
    "Ziarat":           ["Ziarat", "Kawas"],
    "Lasbela":          ["Uthal", "Hub", "Bela"],
    "Jaffarabad":       ["Usta Muhammad", "Gandakha"],
    "Nushki":           ["Nushki City"],
    "Washuk":           ["Kharan", "Washuk City"],
  },
  "Azad Jammu & Kashmir (AJK)": {
    "Muzaffarabad":         ["Muzaffarabad City", "Hattian Bala", "Patika"],
    "Mirpur":               ["Mirpur City", "Dadyal", "Chakswari"],
    "Kotli":                ["Kotli", "Sehnsa", "Charhoi"],
    "Bagh":                 ["Bagh", "Dhirkot"],
    "Rawalakot (Poonch)":   ["Rawalakot", "Abbaspur", "Haveli"],
    "Neelum":               ["Athmuqam", "Sharda", "Kel"],
    "Sudhanoti":            ["Pallandri", "Tain"],
    "Hattian":              ["Hattian Bala City"],
  },
  "Gilgit-Baltistan": {
    "Gilgit":   ["Gilgit City", "Jutial", "Nomal"],
    "Skardu":   ["Skardu City", "Shigar", "Khaplu"],
    "Hunza":    ["Aliabad", "Karimabad", "Gulmit"],
    "Ghizer":   ["Gahkuch", "Yasin", "Phander"],
    "Diamer":   ["Chilas", "Darel", "Tangir"],
    "Astore":   ["Astore", "Gurez"],
    "Nagar":    ["Nagar Valley", "Hispar"],
  },
  "Islamabad Capital Territory": {
    "Islamabad": ["Islamabad City", "Margalla Hills", "Saidpur", "Rawat", "Kahuta (ICT)"],
  },
};

// ─── All official Pakistan education boards ───────────────────────────────────
export const educationBoards = [
  "Federal Board of Intermediate & Secondary Education (FBISE)",
  "BISE Lahore", "BISE Rawalpindi", "BISE Gujranwala", "BISE Sargodha",
  "BISE Faisalabad", "BISE Multan", "BISE DG Khan", "BISE Sahiwal", "BISE Bahawalpur",
  "BISE Karachi", "BISE Hyderabad", "BISE Sukkur", "BISE Larkana", "BISE Mirpurkhas",
  "BISE Peshawar", "BISE Swat", "BISE Mardan", "BISE Abbottabad",
  "BISE Kohat", "BISE DI Khan", "BISE Malakand",
  "BISE Quetta",
  "BISE AJK (Mirpur)",
  "Gilgit-Baltistan Board of Intermediate & Secondary Education",
  "Aga Khan University Examination Board (AKUEB)",
];

// ─── Sports played in Pakistan (U-15 registry) ────────────────────────────────
export const sportsOptions = [
  "Athletics (Track & Field)", "Archery", "Badminton", "Basketball", "Boxing",
  "Cricket", "Cycling", "Football", "Gymnastics", "Hockey", "Judo", "Kabaddi",
  "Shooting", "Squash", "Swimming", "Table Tennis", "Taekwondo", "Tennis",
  "Volleyball", "Weight Lifting", "Wrestling", "Other",
];

// ─── School class levels (U-15 eligible grades) ───────────────────────────────
export const classOptions = ["6th", "7th", "8th", "9th", "10th"];
